"""relaciones y foranea

Revision ID: 0dd939ad25c6
Revises: 67979a1b94ee
Create Date: 2025-06-13 10:29:38.411159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0dd939ad25c6'
down_revision: Union[str, None] = '67979a1b94ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('usuario_revisor_id', sa.Integer(), nullable=True))
    op.add_column('noticias', sa.Column('usuario_escritor_id', sa.Integer(), nullable=True))
    op.drop_constraint('noticias_ibfk_3', 'noticias', type_='foreignkey')
    op.create_foreign_key(None, 'noticias', 'usuarios', ['usuario_escritor_id'], ['id_usuario'])
    op.create_foreign_key(None, 'noticias', 'usuarios', ['usuario_revisor_id'], ['id_usuario'])
    op.drop_column('noticias', 'usuario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.create_foreign_key('noticias_ibfk_3', 'noticias', 'usuarios', ['usuario_id'], ['id_usuario'])
    op.drop_column('noticias', 'usuario_escritor_id')
    op.drop_column('noticias', 'usuario_revisor_id')
    # ### end Alembic commands ###
