"""relaciones y foraneas

Revision ID: 67979a1b94ee
Revises: 250c3f3e8263
Create Date: 2025-06-13 10:20:24.014598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67979a1b94ee'
down_revision: Union[str, None] = '250c3f3e8263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('noticia_id', sa.Integer(), nullable=True))
    op.add_column('comentarios', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comentarios', 'usuarios', ['usuario_id'], ['id_usuario'])
    op.create_foreign_key(None, 'comentarios', 'noticias', ['noticia_id'], ['id_noticia'])
    op.add_column('imagenes', sa.Column('noticia_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'imagenes', 'noticias', ['noticia_id'], ['id_noticia'])
    op.add_column('noticias', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('noticias', sa.Column('comentario_id', sa.Integer(), nullable=True))
    op.add_column('noticias', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'noticias', 'categorias', ['categoria_id'], ['id_categoria'])
    op.create_foreign_key(None, 'noticias', 'comentarios', ['comentario_id'], ['id_comentario'])
    op.create_foreign_key(None, 'noticias', 'usuarios', ['usuario_id'], ['id_usuario'])
    op.add_column('usuarios', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id_rol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'rol_id')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_constraint(None, 'noticias', type_='foreignkey')
    op.drop_column('noticias', 'usuario_id')
    op.drop_column('noticias', 'comentario_id')
    op.drop_column('noticias', 'categoria_id')
    op.drop_constraint(None, 'imagenes', type_='foreignkey')
    op.drop_column('imagenes', 'noticia_id')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_column('comentarios', 'usuario_id')
    op.drop_column('comentarios', 'noticia_id')
    # ### end Alembic commands ###
