"""add noticia table

Revision ID: de4ff2b5cbd9
Revises: 272d7b6e2748
Create Date: 2025-06-09 11:09:52.028485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4ff2b5cbd9'
down_revision: Union[str, None] = '272d7b6e2748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias',
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('titulo', sa.String(length=60), nullable=True),
    sa.Column('introduccion', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.String(length=2000), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_noticia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticias')
    # ### end Alembic commands ###
