"""creo tablas imagen, comentario, usuario y rol con relaciones

Revision ID: f27341a8fc4b
Revises: de4ff2b5cbd9
Create Date: 2025-06-10 17:50:56.821832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27341a8fc4b'
down_revision: Union[str, None] = 'de4ff2b5cbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=60), nullable=True),
    sa.Column('apellido_usuario', sa.String(length=60), nullable=True),
    sa.Column('correo_usuario', sa.String(length=60), nullable=True),
    sa.Column('contrasena_usuario', sa.String(length=60), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=10), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes')
    op.drop_table('comentarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
